### ISSUE TITLE
TypeError: Cannot read property 'browserField' of undefined

### ISSUE THREAD

**Issue by kruncher** [mattdesl/esmify#18]
I have the following in my gulpfile.js:

```js
    return browserify(entryPoint, { debug: isDevelopment })
      .transform('esmify')
```

Which leads to the following error:

> TypeError: Cannot read property 'browserField' of undefined
    at module.exports (C:\Users\leaha\Desktop\git\design-system\node_modules\esmify\esmify.js:20:24)
    at nr (C:\Users\leaha\Desktop\git\design-system\node_modules\module-deps\index.js:315:23)
    at onfile (C:\Users\leaha\Desktop\git\design-system\node_modules\resolve\lib\async.js:146:21)
    at onex (C:\Users\leaha\Desktop\git\design-system\node_modules\resolve\lib\async.js:201:32)
    at C:\Users\leaha\Desktop\git\design-system\node_modules\resolve\lib\async.js:13:20
    at FSReqCallback.oncomplete (fs.js:193:5)
    at FSReqCallback.callbackTrampoline (internal/async_hooks.js:131:17)

**Comment by lejeunerenard** [comment]
I had this issue as well and figured out that I was using a really old version of `browserify` installed globally (`4.1.9` 👴). Once I updated to `17.0.0` it worked. From my investigation of the browserify source, this error should go away starting with `5.0.0` though I recommend upgrading to the latest.

**Comment by jcubic** [comment]
Go the same error with latest browserify 17.0.1 and latest esmify. I use command line:

```bash
npx browserify index.js -o bundle.js -t esmify --standalone ZenFS
```

**Comment by tjconcept** [comment]
@jcubic , did you by chance you `--global-transform / -g` rather than `--plugin / -p`?
